<?php

namespace AppBundle\Repository;

/**
 * derslerdbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class derslerdbRepository extends \Doctrine\ORM\EntityRepository
{
}
