<?php

namespace AppBundle\Repository;

/**
 * donemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class donemRepository extends \Doctrine\ORM\EntityRepository
{
}
