<?php

namespace AppBundle\Repository;

/**
 * egedersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class egedersRepository extends \Doctrine\ORM\EntityRepository
{
}
