<?php

namespace AppBundle\Repository;

/**
 * ogretim_gorevlisidbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ogretim_gorevlisidbRepository extends \Doctrine\ORM\EntityRepository
{
}
